# Generated by Django 5.0.6 on 2024-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=64, unique=True)),
                ('recipient', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('decimals', models.IntegerField()),
                ('value', models.IntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
