# Generated by Django 5.0.6 on 2024-07-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_listener', '0002_tx_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(max_length=200),
        ),
    ]
