# Generated by Django 5.0.6 on 2024-07-24 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_listener', '0003_alter_transaction_recipient_alter_transaction_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tx_counter',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
