# Generated by Django 5.0.6 on 2024-07-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_listener', '0004_tx_counter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tx_counter',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tx_counter',
            name='time',
            field=models.TimeField(),
        ),
    ]
