# Generated by Django 5.0.6 on 2024-07-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_listener', '0004_user_creation_user_creation_counter'),
        ('mqtt_listener', '0005_alter_tx_counter_date_alter_tx_counter_time'),
    ]

    operations = [
    ]
