# Generated by Django 5.0.6 on 2024-07-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_listener', '0006_wallet_wallet_counter_wallet_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet_Test',
        ),
    ]
