# Generated by Django 5.0.6 on 2024-07-26 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_listener', '0008_wallet_country_wallet_currency_wallet_language'),
        ('paytaca_map', '0002_location_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('rider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_time', models.DateTimeField()),
                ('delivered_time', models.DateTimeField()),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytaca_map.merchant')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt_listener.rider')),
            ],
        ),
    ]
