# Generated by Django 5.0.6 on 2024-07-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytaca_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchtower_merchant_id', models.IntegerField(null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('gmap_business_link', models.URLField(blank=True, null=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('town', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('logo_size', models.CharField(max_length=10, null=True)),
                ('logo_url', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'ordering': ['-last_transaction_date'],
            },
        ),
    ]
