# Generated by Django 5.0.6 on 2024-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytaca_map', '0002_merchantinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchantInfo',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='receiving_address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='receiving_pubkey',
        ),
        migrations.AddField(
            model_name='merchant',
            name='category_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='logo_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='town',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
