# Generated by Django 5.0.6 on 2024-07-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytaca_map', '0003_delete_merchantinfo_remove_merchant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
