# Generated by Django 5.0.6 on 2024-07-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytaca_map', '0004_merchant_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
